---
title: "rs-ws-02-2"
author: "MOC - Data Analysis (T. Nauss, C. Reudenbach)"
date: "20. Oktober 2016"
output: html_document
---

Kappa
```{r, eval=FALSE}
# Set path ---------------------------------------------------------------------
if(Sys.info()["sysname"] == "Windows"){
  filepath_base <- "D:/active/moc/msc-phygeo-remote-sensing-2016/"
} else {
  filepath_base <- "/media/permanent/active/moc/msc-phygeo-remote-sensing-2016/"
}

path_data <- paste0(filepath_base, "data/")
path_landcover <- paste0(path_data, "landcover/")
path_rdata <- paste0(path_data, "RData/")
path_scripts <- paste0(filepath_base, "scripts/msc-phygeo-remote-sensing/src/functions/")
path_temp <- paste0(filepath_base, "temp/")

funs <- list.files(path_scripts, pattern = glob2rx("fun*.R"), full.names = TRUE)
sapply(funs, source, simplify = TRUE)


# Read confusion matrix -------------------------------------------------------
cm <- read.table(paste0(path_landcover, "lc.csv"), skip = 2, header = FALSE,
                 sep = ",")
colnames(cm) <- paste("ID_", seq(5))
rownames(cm) <- paste("ID_", seq(5))

kappa <- compKappa(cm)
```

### Compute kappa
```{r}
compKappa <- function(ctable){
  ctable <- ctable/sum(ctable)
  categories <- nrow(ctable)
  
  # Fraction of agreement
  pagrm <- 0
  for(i in seq(categories)){
    pagrm <- pagrm + ctable[i,i]
  }
  
  # Expected fraction of agreement subject to the observed distribution
  pexpct <- 0
  for(i in seq(categories)){
    pexpct <- pexpct + sum(ctable[i,]) * sum(ctable[,i])
  }
  
  # Kappa index
  kappa <- (pagrm - pexpct)/(1 - pexpct)
  return(kappa)
}
```
