---
title: "rs-ws-02-2"
author: "MOC - Data Analysis (T. Nauss, C. Reudenbach)"
date: "20. Oktober 2016"
output: html_document
---

Kappa
```{r, eval=FALSE}
# Set environment --------------------------------------------------------------
if(Sys.info()["sysname"] == "Windows"){
  source("D:/active/moc/msc-ui/scripts/msc-phygeo-ei/src/functions/set_environment.R")
} else {
  source("/media/permanent/active/moc/msc-ui/scripts/msc-phygeo-ei/src/functions/set_environment.R")
}

# Read confusion matrix -------------------------------------------------------
cm <- read.table(paste0(path_landcover, "lc.csv"), skip = 2, header = FALSE,
                 sep = ",")
colnames(cm) <- paste("ID_", seq(5))
rownames(cm) <- paste("ID_", seq(5))

kappa <- compKappa(cm)
```

### Compute kappa
```{r}
compKappa <- function(ctable){
  ctable <- ctable/sum(ctable)
  categories <- nrow(ctable)
  
  # Fraction of agreement
  pagrm <- 0
  for(i in seq(categories)){
    pagrm <- pagrm + ctable[i,i]
  }
  
  # Expected fraction of agreement subject to the observed distribution
  pexpct <- 0
  for(i in seq(categories)){
    pexpct <- pexpct + sum(ctable[i,]) * sum(ctable[,i])
  }
  
  # Kappa index
  kappa <- (pagrm - pexpct)/(1 - pexpct)
  return(kappa)
}
```
